title: Built With
app:
  name: Built With
  author: 'Phalcon Team'
  description: ''
  keywords: ''
  avatar: https://avatars3.githubusercontent.com/u/1221505?v=4

social:
  email: team@phalconphp.com
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

meta:
  disqus:
    name: ''
    url: ''
  analytics: 'UA-133802124-8'

excerpt_separator: <!--more-->

paginate: 5
paginate_path: '/page-:num'

permalink: /project/:title
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



